In [1]:
# Import dependencies
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st

odb2014_path = "../2014OpenData.csv"

odb2014 = pd.read_csv("../2014OpenData.csv")

In [3]:
odb2014.head()

,Year,Region,Income,ISO2,ISO3,ODB-Rank,Country,ODB-Score,Readiness,Implementation,...,Impact_Economic-Scaled,HDI,G20,G7,GDP-Per-Capita-Current-USD,2013-Rank,2013-ODB-Scaled,ODB Change,Rank Change,Cluster
0,2014,Middle East & North Africa,High income,AE,ARE,52,UAE,-0.113555,-0.011659,-0.480576,...,0,0.827,NaN,NaN,NaN,NaN,NaN,NaN,NaN,One sided initiative
1,2014,Latin America & Caribbean,Upper middle income,AR,ARG,36,Argentina,0.023207,-0.174486,0.187631,...,20,0.808,G20,NaN,14715.18002,31.0,35.00,0.71,-5.0,Emerging and advancing
2,2014,East Asia & Pacific,High income,AU,AUS,10,Australia,0.434557,1.185518,1.657688,...,40,0.933,G20,NaN,67468.06871,7.0,67.68,0.65,-3.0,High capacity
3,2014,Europe & Central Asia,High income,AT,AUT,15,Austria,0.310956,0.906397,0.421504,...,59,0.881,NaN,NaN,49053.82290,18.0,46.03,12.49,3.0,High capacity
4,2014,Europe & Central Asia,High income,BE,BEL,27,Belgium,0.169248,1.013088,-0.113062,...,61,0.881,NaN,NaN,45387.17553,31.0,34.80,12.49,4.0,High capacity